"""Create initial tables

Revision ID: a0b361340092
Revises: c346b388f004
Create Date: 2025-06-29 12:24:06.938491

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "a0b361340092"
down_revision: str | None = "c346b388f004"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("email", sa.String(length=255), nullable=False),
        sa.Column("hashed_password", sa.String(length=255), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_email"), "users", ["email"], unique=True)
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_index(op.f("ix_users_username"), "users", ["username"], unique=True)
    op.create_table(
        "admin_actions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("admin_user_id", sa.Integer(), nullable=False),
        sa.Column("action", sa.String(length=50), nullable=False),
        sa.Column("target_user_id", sa.Integer(), nullable=True),
        sa.Column("action_details", sa.Text(), nullable=True),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["admin_user_id"],
            ["users.id"],
        ),
        sa.ForeignKeyConstraint(
            ["target_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_admin_actions_action_timestamp",
        "admin_actions",
        ["action", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_admin_actions_admin_timestamp",
        "admin_actions",
        ["admin_user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_admin_actions_target_timestamp",
        "admin_actions",
        ["target_user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_actions_action"), "admin_actions", ["action"], unique=False
    )
    op.create_index(
        op.f("ix_admin_actions_admin_user_id"),
        "admin_actions",
        ["admin_user_id"],
        unique=False,
    )
    op.create_index(op.f("ix_admin_actions_id"), "admin_actions", ["id"], unique=False)
    op.create_index(
        op.f("ix_admin_actions_target_user_id"),
        "admin_actions",
        ["target_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_admin_actions_timestamp"), "admin_actions", ["timestamp"], unique=False
    )
    op.create_table(
        "gift_events",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("from_user_id", sa.Integer(), nullable=False),
        sa.Column("gift_id", sa.String(length=50), nullable=False),
        sa.Column("amount", sa.Integer(), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["from_user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_gifts_type_timestamp",
        "gift_events",
        ["gift_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_gifts_user_timestamp",
        "gift_events",
        ["from_user_id", "timestamp"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gift_events_from_user_id"),
        "gift_events",
        ["from_user_id"],
        unique=False,
    )
    op.create_index(
        op.f("ix_gift_events_gift_id"), "gift_events", ["gift_id"], unique=False
    )
    op.create_index(op.f("ix_gift_events_id"), "gift_events", ["id"], unique=False)
    op.create_index(
        op.f("ix_gift_events_timestamp"), "gift_events", ["timestamp"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("message_text", sa.Text(), nullable=False),
        sa.Column("toxicity_flag", sa.Boolean(), nullable=False),
        sa.Column("toxicity_score", sa.Float(), nullable=True),
        sa.Column("message_type", sa.String(length=20), nullable=False),
        sa.Column("timestamp", sa.DateTime(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        "idx_messages_toxicity_timestamp",
        "messages",
        ["toxicity_flag", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_messages_type_timestamp",
        "messages",
        ["message_type", "timestamp"],
        unique=False,
    )
    op.create_index(
        "idx_messages_user_timestamp",
        "messages",
        ["user_id", "timestamp"],
        unique=False,
    )
    op.create_index(op.f("ix_messages_id"), "messages", ["id"], unique=False)
    op.create_index(
        op.f("ix_messages_message_type"), "messages", ["message_type"], unique=False
    )
    op.create_index(
        op.f("ix_messages_timestamp"), "messages", ["timestamp"], unique=False
    )
    op.create_index(
        op.f("ix_messages_toxicity_flag"), "messages", ["toxicity_flag"], unique=False
    )
    op.create_index(op.f("ix_messages_user_id"), "messages", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_user_id"), table_name="messages")
    op.drop_index(op.f("ix_messages_toxicity_flag"), table_name="messages")
    op.drop_index(op.f("ix_messages_timestamp"), table_name="messages")
    op.drop_index(op.f("ix_messages_message_type"), table_name="messages")
    op.drop_index(op.f("ix_messages_id"), table_name="messages")
    op.drop_index("idx_messages_user_timestamp", table_name="messages")
    op.drop_index("idx_messages_type_timestamp", table_name="messages")
    op.drop_index("idx_messages_toxicity_timestamp", table_name="messages")
    op.drop_table("messages")
    op.drop_index(op.f("ix_gift_events_timestamp"), table_name="gift_events")
    op.drop_index(op.f("ix_gift_events_id"), table_name="gift_events")
    op.drop_index(op.f("ix_gift_events_gift_id"), table_name="gift_events")
    op.drop_index(op.f("ix_gift_events_from_user_id"), table_name="gift_events")
    op.drop_index("idx_gifts_user_timestamp", table_name="gift_events")
    op.drop_index("idx_gifts_type_timestamp", table_name="gift_events")
    op.drop_table("gift_events")
    op.drop_index(op.f("ix_admin_actions_timestamp"), table_name="admin_actions")
    op.drop_index(op.f("ix_admin_actions_target_user_id"), table_name="admin_actions")
    op.drop_index(op.f("ix_admin_actions_id"), table_name="admin_actions")
    op.drop_index(op.f("ix_admin_actions_admin_user_id"), table_name="admin_actions")
    op.drop_index(op.f("ix_admin_actions_action"), table_name="admin_actions")
    op.drop_index("idx_admin_actions_target_timestamp", table_name="admin_actions")
    op.drop_index("idx_admin_actions_admin_timestamp", table_name="admin_actions")
    op.drop_index("idx_admin_actions_action_timestamp", table_name="admin_actions")
    op.drop_table("admin_actions")
    op.drop_index(op.f("ix_users_username"), table_name="users")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_index(op.f("ix_users_email"), table_name="users")
    op.drop_table("users")
    # ### end Alembic commands ###
