"""add_is_streamer_flag_to_users

Revision ID: db7517b5a359
Revises: 2ced2aeb79df
Create Date: 2025-06-30 14:56:12.773887

"""

from collections.abc import Sequence

# revision identifiers, used by Alembic.
revision: str = "db7517b5a359"
down_revision: str | None = "2ced2aeb79df"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
